source 'https://rubygems.org'
gem 'boson'
gem 'boson-more'
gem 'alias'
gem 'bond'
gem 'hirb'
gem 'menu'
#gem 'termios'
gem 'method_lister'
gem 'keychain'

# Commandline tools
#gem 'wolf'
#gem 'vimdb'
#gem 'urls'
#gem 'tag'
#gem 'wolfram'

gem 'ripl'
gem 'ripl-ripper'
gem 'ripl-color_error'
gem 'ripl-commands'
gem 'ripl-after_rc'
gem 'ripl-i18n'
#gem 'https://github.com/cldwalker/ripl-misc'
