---
:pager_command: less -r
:output:
  Grit::Commit:
    :options:
      :fields:
      - committed_date
      - author
      - message
  WWW::Delicious::Post:
    :options:
      :fields:
      - :url
      - :notes
      - :time
  WWW::Delicious::Tag:
    :options:
      :fields:
      - :name
      - :count
  WWW::Delicious::Bundle:
    :options:
      :fields:
      - :name
      - :tags
      :filters:
        :tags:
        - join
        - ','
  WWW::Delicious::Element:
    :ancestor: true
    :class: :object_table
  Gem::Specification:
    :class: :object_table
    :options:
      :fields:
      - name
      - description
      - homepage
  RDF::Statement:
    :class: :object_table
    :options:
      :fields:
      - subject
      - predicate
      - object
  ActiveRecord::Errors:
    :class: :active_record_errors
